### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [bzavadil/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the page looks good. You used some good techniques here. Check out the issues I created and see if you can implement the suggestions. Projects are going to get much larger and more complex in the next Units so being organized and efficient will be very important. Here are some good tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by bzavadil** [comment]
Hi Ryan--thanks for the review of this.  Great having someone look everything over, and most of the issues were one's that I was unsure of, so it's great to have clarification on items that were in question.  Thanks!
